### ISSUE TITLE
Not sending alerts - using Flowdock adapter

### ISSUE THREAD

**Issue by victorhooi** [hubot-scripts/hubot-standup-alarm#2]
I have a Hubot 2.8.2 instance running, using the hubot-flowdock adapter.

I attempted to add a standup alarm for 11:16 - but it didn't seem to trigger. I see the below in the logs:

```
[Tue Sep 30 2014 11:16:02 GMT+1000 (EST)] ERROR TypeError: Cannot read property 'metadata' of undefined
  at Flowdock.send (/Users/victorhooi/code/foobar-glados/node_modules/hubot-flowdock/src/flowdock.coffee:13:5, <js>:31:55)
  at Robot.messageRoom (/Users/victorhooi/code/foobar-glados/node_modules/hubot/src/robot.coffee:410:19, <js>:380:42)
  at doStandup (/Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/scripts/standup.js:97:15)
  at /Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/scripts/standup.js:89:17
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/node_modules/underscore/underscore.js:79:11)
  at checkStandups (/Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/scripts/standup.js:87:11)
  at Object.<anonymous> (/Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/scripts/standup.js:39:9)
  at Object.CronJob._callback (/Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/node_modules/cron/lib/cron.js:339:26)
  at [object Object].callbackWrapper [as _onTimeout] (/Users/victorhooi/code/foobar-glados/node_modules/hubot-standup-alarm/node_modules/cron/lib/cron.js:401:14)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by shaundon** [comment]
Should be fixed in https://github.com/hubot-scripts/hubot-standup-alarm/commit/d3608051d11a8df1cf8d051805f152f90e5868c4.
